name: Wiki.js Sync

on:
  push:
    branches:
      - main

jobs:
  force-wikijs-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Purge Git Storage
        run: |
          curl -X POST "https://docs.vasseurlaurent.com/graphql" \
            -H "Authorization: Bearer ${{ secrets.WIKIJS_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation { adminStorageGitPurge }"}'

      - name: Import Git Storage
        run: |
          curl -X POST "https://docs.vasseurlaurent.com/graphql" \
            -H "Authorization: Bearer ${{ secrets.WIKIJS_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation { adminStorageGitImport }"}'

      - name: Force Sync Git Storage
        run: |
          curl -X POST "https://docs.vasseurlaurent.com/graphql" \
            -H "Authorization: Bearer ${{ secrets.WIKIJS_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "mutation { adminStorageGitForceSync }"}'
